title: DSTL Onboarding
description: Onboarding guide for new members
theme: just-the-docs

url: https://dstl.ucsd.edu/onboarding


aux_links:
  repo: https://github.com/dstl-lab/onboarding

# https://just-the-docs.com/docs/configuration/#callouts
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

plugins:
  - jekyll-target-blank
